/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guipages;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dnyanesh
 */
public class viewcandidate extends javax.swing.JFrame {

    /**
     * Creates new form viewcandidate
     */
    public viewcandidate() {
        initComponents();
        getEntries();
    }
 private void getEntries(){
        try{
            javax.swing.table.DefaultTableModel dtm = 
                         (javax.swing.table.DefaultTableModel) candtable.getModel();
             int rc = dtm.getRowCount();
             while(rc--!=0){
                 dtm.removeRow(0);
             }
            
            
             ResultSet rs=db.dbconnect.st.executeQuery("select * from candidate");
             int sno=0;
             while(rs.next()){
                 int  candid = rs.getInt("candid");
                 String jobid = rs.getString("jobid");
                 String jobname = rs.getString("jobname");
                
                 String deptid = rs.getString("deptid");
                 String firstname = rs.getString("firstname");
                 String lastname = rs.getString("lastname");
                 String memberid = rs.getString("MemberID");
                
                 Object o[]={candid,jobid,jobname,deptid,firstname,lastname,memberid};
                 dtm.addRow(o);
             }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        candtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        candtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cand ID", "Job ID", "Job Name", "Dept ID", "First Name", "Last Name", "MemberID"
            }
        ));
        jScrollPane1.setViewportView(candtable);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD AS EMPLOYEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String emailid ;
           String phoneno ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ri = candtable.getSelectedRow();
       if(ri!=1){
       
       
       
                
        String jobid1= (String)candtable.getValueAt(ri,1);
        String jobname1 = (String)candtable.getValueAt(ri,2);
        String deptid1 = (String)candtable.getValueAt(ri,3);
        String firstname1 = (String)candtable.getValueAt(ri,4);
        String lastname1 = (String)candtable.getValueAt(ri,5);
        String memberid1= (String)candtable.getValueAt(ri,6);
        //String deptname = (String)jobtable.getValueAt(ri,4);
         
        try{
           ResultSet rs1 =   db.dbconnect.st.executeQuery("select * from candidate  inner join signup on candidate.MemberID= signup.MemberID where candidate.MemberID = '"+memberid1+"'");
          
          
          int count = 0;
         
           while(rs1.next()){
                 phoneno = rs1.getString("PhoneNo");
                emailid = rs1.getString("EmailID");
               ////count++;
              
            // JOptionPane.showMessageDialog(null,"Added successfully");
             
           
              
                
          }
           db.dbconnect.st.executeUpdate("insert into employee(firstname,lastname,deptid,phoneno,emailid,MemberID) values"
                     + "('"+firstname1+"','"+lastname1+"','"+deptid1+"','"+emailid+"','"+phoneno+"','"+memberid1+"')");
           JOptionPane.showMessageDialog(null,"Added successfully");
           
             
//             db.dbconnect.st.executeUpdate("insert into employee(firstname,lastname,deptid,deptname,phoneno,emailid) values"
//                     + "('"+firstname+"','"+lastname+"','"+deptid+"','"+depname+"','"+phoneno+"','"+emailid+"')");
//             JOptionPane.showMessageDialog(null,"Applied successfully");
            // getEntries();
           
        }catch(Exception ex){
           
            
             
            JOptionPane.showMessageDialog(null,ex);
        } 
//        try{
//             ResultSet rs2 = db.dbconnect.st.executeQuery("Select * from jobs where jobid = '"+jobid1+"' ") ;
//          
//            while(rs2.next()){
//             String  depname = rs2.getString("depname");
//             db.dbconnect.st.executeUpdate("update employee set deptname = '"+depname+"' where deptid = '"+deptid1+"' ");
//              JOptionPane.showMessageDialog(null,"Added successfully");
//          }
//                     
//             
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null,ex);
//        }
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewcandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewcandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewcandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewcandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewcandidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable candtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
